language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - pypy
# command to run tests
script:
 # work around https://bitbucket.org/hpk42/pytest/issue/555
 - sudo easy_install 'pytest<2.6'
 - python setup.py test
 - python setup.py ptr
 - python ez_setup.py --version 5.4.1
