language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy
env:
 - LC_ALL=C PYTHONHASHSEED=0
script:
 # update egg_info based on setup.py in checkout
 - python bootstrap.py

 - python setup.py test --addopts='-rs'
 - python ez_setup.py --version 18.6.1
